### ISSUE TITLE
unexpected result komi 6.5 results in draw and possibly suspicious sgf submitted to server

### ISSUE THREAD

**Issue by codingnewcode** [katago/katago-server#116]
this game (https://katagotraining.org/sgfplayer/rating-games/1279994/) has result "draw" which should be impossible with a komi of 6.5 unless i'm mistaken

it's a match game, parsed in https://katagotraining.org/networks/kata1/kata1-b18c384nbt-s9791399168-d4261348054/rating-games/ ,  also the moves are slightly supsicious (unusual at least i would say i mean) even though this is subjective

other games uploaded by the same user seem to show weird or at least unusual joseki and game even though this is subjective too and may be just my impression or not etc in : https://katagotraining.org/sgfplayer/rating-games/1279992/

**Comment by lightvector** [comment]
@codingnewcode Thanks for the question and for keeping an eye on things! I hope the games and stats and results have been fun to look at.

I don't think I see any issue with this game. KataGo randomizes between many possible rulesets for Go, and this is a game of "Button Go", (https://senseis.xmp.net/?ButtonGo), which you can see at the bottom in the rules to the game, `'hasButton': True`. So because of the button (awarded to the first player to pass), the score will be an integer and draw is possible.

Are there specific moves that you still find unusual?

**Comment by codingnewcode** [comment]
thanks @lightvector for your quick reply and feedback explanation

i enjoy looking at these games but i am glad it can help too i mean

i see i understand from your explanation thanks, some moves seemed slightly off such as (in the second link i sent) 24 25 38 39 43 47 55 mainly from the opening and early game but they are not nonsensical just a bit unusual but if the game is legitimate and not malicious then they should make sense (plus they are even according to AI), also i am overall quite a bit weaker than 1d so this is just my opinion that could be mistaken too, in all cases thanks, if you have a question you could ask me too, else i would consider this issue solved, thanks again i all cases for your feedbakc, i like watching these games, but that being said i could close this issue if this is solved thanks i mean
